name: ModSimPy

dependencies:
  - python=3.7
  - jupyter
  - numpy
  - matplotlib
  - seaborn
  - pandas
  - scipy
  - pint
  - sympy
  - lxml
  - html5lib
  - beautifulsoup4
  - pytables
  
  
  




