name: ModSimPy
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.6
  - jupyter
  - numpy
  - matplotlib
  - seaborn
  - pandas
  - scipy
  - pint
  - sympy
  - lxml
  - html5lib
  - beautifulsoup4
  - pytables
  
  
  




